#Database
spring:
  #DB
  datasource:
    url: ${WHISPER_DB_URL:?Database url not set}
    username: ${WHISPER_DB_USERNAME:?Database username not set}
    password: ${WHISPER_DB_PASSWORD:?Database password not set}
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: ${SCHEMA_NAME:public}
      maximum-pool-size: ${POSTGRES_POOL_SIZE:2}
  #JPA
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    show-sql: ${WHISPER_SHOW_SQL:false}
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  #Liquibase
  liquibase:
    drop-first: true
    change-log: classpath:db/changelog/db.changelog.xml
    enabled: true
    default-schema: ${SCHEMA_NAME:public}
    contexts: default