# Server
server:
  port: ${WHISPER_SERVER_PORT:8080}

# Spring
spring:
  profiles:
    include:
      - db
  application:
    name: '@project.artifactId@-@project.version@'

# OpenAPI
springdoc:
  api-docs:
    path: /api-docs
